import apple from '../../assets/Apple.png'
import samsung from '../../assets/Samsung.png'
import nokia from '../../assets/Nokia.png'
import amazon from '../../assets/Amazon.png'

export const brands = [
    {img: apple,
    to: '/apple-phones'},
    {img: samsung,
    to: '/samsung-phones'},
    {img: nokia,
    to: '/nokia-phones'},
    {img: amazon,
    to: '/tecno-phones'}
]

export const phoneDatas = [{
    name: 'Iphone 6',
    brand: 'apple',
    brandImg: apple,
    category: 'phone',
    storage: [16, 32, 64],
    ram: [1,2,4],
},
{
    name: 'Iphone 6s',
    brand: 'apple',
    brandImg: apple,
    category: 'phone',
    storage: [16, 32, 64],
    ram: [2,4],
},
{
    name: 'Iphone 6 Plus',
    brand: 'apple',
    brandImg: apple,
    category: 'phone',
    storage: [16, 32, 64],
    ram: [2,4],
},
{
    name: 'Iphone 6s Plus',
    brand: 'apple',
    brandImg: apple,
    category: 'phone',
    storage: [16, 32, 64, 128],
    ram: [2,4],
},
{
    name: 'Iphone 7',
    brand: 'apple',
    BrandImg: apple,
    category: 'phone',
    storage: [16, 32, 128],
    ram: [2,4],
},
{
    name: 'Iphone 7 Plus',
    brand: 'apple',
    brandImg: apple,
    category: 'phone',
    storage: [16, 32, 128, 256],
    ram: [2,4],
},
{
    name: 'Iphone 8',
    brand: 'apple',
    brandImg: apple,
    category: 'phone',
    storage: [16, 32, 64, 128, 256],
    ram: [2,4],
},
{
    name: 'Iphone 8 Plus',
    brand: 'apple',
    brandImg: apple,
    category: 'phone',
    storage: [16, 32, 64, 128, 256],
    ram: [2,4],
},
{
    name: 'Iphone 6',
    brand: 'apple',
    img: apple,
    category: 'phone',
    storage: [16, 32, 64],
    ram: [1,2,4],
},
{
    name: 'Iphone 6',
    brand: 'apple',
    img: apple,
    category: 'phone',
    storage: [16, 32, 64],
    ram: [1,2,4],
},
{
    name: 'Iphone 6',
    brand: 'apple',
    img: apple,
    category: 'phone',
    storage: [16, 32, 64],
    ram: [1,2,4],
},
{
    name: 'Iphone 6',
    brand: 'apple',
    img: apple,
    category: 'phone',
    storage: [16, 32, 64],
    ram: [1,2,4],
},
{
    name: 'Iphone 6',
    brand: 'apple',
    img: apple,
    category: 'phone',
    storage: [16, 32, 64],
    ram: [1,2,4],
},
{
    name: 'Iphone 6',
    brand: 'apple',
    img: apple,
    category: 'phone',
    storage: [16, 32, 64],
    ram: [1,2,4],
},
{
    name: 'Iphone 6',
    brand: 'apple',
    img: apple,
    category: 'phone',
    storage: [16, 32, 64],
    ram: [1,2,4],
},
]