import {
  laptopBrands,
  phoneBrands,
  computerBrands,
  smartSpeakerBrands,
  smartWatchbrands,
  tvBrands,
  gamingGadgetBrands,
  cameraBrands,
} from "../components/Pages/PhoneData";
import appl from "../assets/tecnoSpark4.jpg";
const localCurrentUser = localStorage.getItem("user");
const sessionSR = sessionStorage.getItem("result");
const selectedDevice = JSON.parse(localStorage.getItem("userSelected"));
export const defaultState = {
  toggle: false,
  modalContent: "",
  isModal: false,
  usedGadgets: [],
  allGadgets: [
    {
      img: appl,
      id: 1,
      name: "iphone 6",
      price: 45000,
      brand: { value: "apple" },
      category: { value: "phones" },
      storage: { value: "209873" },
      desc: "Fugiat ipsum culpa aliquip nulla est.Et qui aliquip non nisi duis cupidatat pariatur dolor eu culpa sint exercitation consequat consequat.",
    },
    {
      img: appl,
      id: 2,
      name: "Tecno camon 5",
      price: 15000,
      brand: { value: "tecno" },
      category: { value: "phones" },
      storage: { value: "10000873" },
      desc: "Fugiat ipsum culpa aliquip nulla est.Et qui aliquip non nisi duis cupidatat pariatur dolor eu culpa sint exercitation consequat consequat.",
    },
  ],
  phoneBrands: phoneBrands,
  laptopBrands: laptopBrands,
  computerBrands: computerBrands,
  smartSpeakerBrands: smartSpeakerBrands,
  smartWatchbrands: smartWatchbrands,
  tvBrands: tvBrands,
  gamingGadgetBrands: gamingGadgetBrands,
  cameraBrands: cameraBrands,
  orders: [],
  selectedDevice: selectedDevice ? [selectedDevice] : [],
  newSelected: [],
  city: localStorage.getItem("city") ? localStorage.getItem("city") : "",
  isCity: localStorage.getItem("city") ? false : true,
  isMainCity: false,
  allCities: [],
  currentUser: localCurrentUser ? JSON.parse(localCurrentUser) : {},
  isUser: localCurrentUser ? true : false,
  searchResult: sessionSR ? JSON.parse(sessionSR) : [],
  repairDataAdmin: [],
};
